name: Delete Environment (default settings)
on:
  pull_request:
    types:
      - closed
    
jobs:
  delete:
    runs-on: ubuntu-latest
    steps:
      - uses: strumwolf/delete-deployment-environment@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          environment: Production
